name: Elixir CI
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    name: Linux OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      fail-fast: false
      matrix:
        pair:
          - otp-version: '25.0'
            elixir-version: '1.14'
          - otp-version: '24.1'
            elixir-version: '1.14'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.pair.otp-version}}
        elixir-version: ${{matrix.pair.elixir-version}}
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
